### ISSUE TITLE
Support finding the aurora master via zookeeper

### ISSUE THREAD

**Issue by SEJeff** [benley/aurora-jobhopper#3]
When you enable an announcer in Aurora with the default flags (serversets under /aurora), the scheduler writes out where it is.

An example session in `zkCli.sh`:

``` bash
[zk: localhost:2181(CONNECTED) 0] ls /aurora/scheduler
[member_0000000125, singleton_candidate_0000000124, singleton_candidate_0000000123, singleton_candidate_0000000126]
[zk: localhost:2181(CONNECTED) 1] get /aurora/scheduler/member_0000000125
{"serviceEndpoint":{"host":"njb-mesosl5.internal","port":8081},"additionalEndpoints":{"http":{"host":"njb-mesosl5.internal","port":8081}},"status":"ALIVE"}
cZxid = 0x1f00000521
ctime = Mon Jul 06 16:13:20 CDT 2015
mZxid = 0x1f00000521
mtime = Mon Jul 06 16:13:20 CDT 2015
pZxid = 0x1f00000521
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x34d73d932a40097
dataLength = 177
numChildren = 0
```

This would allow using jobhopper when running aurora in high availability mode with multiple schedulers.

**Comment by benley** [comment]
That makes a ton of sense and I'm surprised I didn't think of doing that the first time around.  The frontend that I've got in front of the aurora scheduler already finds the scheduler instances that way!

**Comment by SEJeff** [comment]
Not sure that I'll have time to implement this myself anytime soon, but if you get some free cycles, that would be :beer: worthy

**Comment by benley** [comment]
This is probably coming up soon.

**Comment by benley** [comment]
@SEJeff I finally did this :-)

**Comment by SEJeff** [comment]
Yay thanks!
